# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_bytetrunc_wrappers", use_symbols = TRUE, package_name = "bytetrunc")

#' @docType package
#' @usage NULL
#' @useDynLib bytetrunc, .registration = TRUE
NULL

byte_trunc_ <- function(string, size) .Call(wrap__byte_trunc_, string, size)

